language: clojure
jdk:
  - oraclejdk8

before_deploy: lein uberjar
deploy:
  provider: releases
  api_key: "${GH_TOKEN}"
  file: ./target/uberjar/*standalone.jar
  skip_cleanup: true
  on:
    tags: true
