language: clojure
jdk:
  - openjdk7
  - oraclejdk7
  - oraclejdk8

before_deploy:
  - lein jar
  - lein deploy releases
deploy:
  provider: releases
  api_key: "${GH_TOKEN}"
  file_glob: true
  file: $TRAVIS_BUILD_DIR/target/*.jar
  skip_cleanup: true
  overwrite: true
  on:
    tags: true