language: clojure
jdk:
  - oraclejdk8

before_deploy:
  - lein uberjar
deploy:
  provider: releases
  api_key: "${GH_TOKEN}"
  file_glob: true
  file: $TRAVIS_BUILD_DIR/target/uberjar/*standalone.jar
  skip_cleanup: true
  overwrite: true
  on:
    tags: true
